export const AUDIO_FILES = {
  "01. Select Your Champion": "voice_01_select_your_champion.wav",
  "02. Fight": "voice_02_fight.wav",
  "03. Embrace the Fury": "voice_03_embrace_the_fury.wav",
  "04. Fear is Weakness": "voice_04_fear_is_weakness.wav",
  "05. Apocalypse": "voice_05_apocalypse.wav",
  "07. Pathetic": "voice_07_pathetic.wav",
  "08. Berserk": "voice_08_berserk.wav",
  "09. First Round": "voice_09_first_round.wav",
  "10. Second Round": "voice_10_second_round.wav",
  "11. Third Round": "voice_11_third_round.wav",
  "12. Death Round": "voice_12_death_round.wav",
  "13. Death Match": "voice_13_death_match.wav",
  "14. Victor": "voice_14_victor.wav",
  "15. Sudden Death": "voice_15_sudden_death.wav",
  "16. Knockout": "voice_16_knockout.wav",
  "17. KO": "voice_17_ko.wav",
  "18. You Died": "voice_18_you_died.wav",
  "19. I Demand a Sacrifice": "voice_19_i_demand_a_sacrifice.wav",
  "20. Disappointing": "voice_20_disappointing.wav",
  "21. Savagery": "voice_21_savagery.wav",
  "22. Execution": "voice_22_execution.wav",
  "23. Finality": "voice_23_finality.wav",
  "24. Ferocity": "voice_24_ferocity.wav",
  "25. Decimation": "voice_25_decimation.wav",
  "26. Rage Fuel": "voice_26_rage_fuel.wav",
  "27. Vicious": "voice_27_vicious.wav",
  "28. Game Over": "voice_28_game_over.wav",
  "blade_hit_07": "blade_hit_07.wav",
  "blade_hit_08": "blade_hit_08.wav",
  "block_large_59": "block_large_59.wav",
  "block_large_71": "block_large_71.wav",
  "block_medium_09": "block_medium_09.wav",
  "block_medium_25": "block_medium_25.wav",
  "block_small_69": "block_small_69.wav",
  "block_small_73": "block_small_73.wav",
  "body_hit_finisher_23": "body_hit_finisher_23.wav",
  "body_hit_finisher_27": "body_hit_finisher_27.wav",
  "body_hit_finisher_42": "body_hit_finisher_42.wav",
  "body_hit_finisher_52": "body_hit_finisher_52.wav",
  "body_hit_large_32": "body_hit_large_32.wav",
  "body_hit_large_44": "body_hit_large_44.wav",
  "body_hit_large_76": "body_hit_large_76.wav",
  "body_hit_small_11": "body_hit_small_11.wav",
  "body_hit_small_20": "body_hit_small_20.wav",
  "body_hit_small_23": "body_hit_small_23.wav",
  "body_hit_small_79": "body_hit_small_79.wav",
  "bone_breaking_03": "bone_breaking_03.wav",
  "bone_breaking_53": "bone_breaking_53.wav",
  "face_hit_finisher_19": "face_hit_finisher_19.wav",
  "face_hit_finisher_40": "face_hit_finisher_40.wav",
  "face_hit_finisher_61": "face_hit_finisher_61.wav",
  "face_hit_finisher_73": "face_hit_finisher_73.wav",
  "face_hit_Large_20": "face_hit_large_20.wav",
  "face_hit_Large_29": "face_hit_large_29.wav",
  "face_hit_Large_78": "face_hit_large_78.wav",
  "face_hit_small_01": "face_hit_small_01.wav",
  "face_hit_small_13": "face_hit_small_13.wav",
  "face_hit_small_23": "face_hit_small_23.wav",
  "face_hit_small_78": "face_hit_small_78.wav",
  "fire_punch_02": "fire_punch_02.wav",
  "fire_punch_finisher_06": "fire_punch_finisher_06.wav",
  "guts_and_gore_19": "guts_and_gore_19.wav",
  "guts_and_gore_59": "guts_and_gore_59.wav",
  "guts_and_gore_68": "guts_and_gore_68.wav",
  "kick_long_whoosh_19": "kick_long_whoosh_19.wav",
  "kick_short_whoosh_12": "kick_short_whoosh_12.wav",
  "kick_short_whoosh_23": "kick_short_whoosh_23.wav",
  "metal_punch_06": "metal_punch_06.wav",
  "metal_punch_finisher_07": "metal_punch_finisher_07.wav",
  "punch_long_whoosh_21": "punch_long_whoosh_21.wav",
  "punch_long_whoosh_30": "punch_long_whoosh_30.wav",
  "punch_short_whoosh_16": "punch_short_whoosh_16.wav",
  "punch_short_whoosh_30": "punch_short_whoosh_30.wav",
  "somersault_01": "somersault_01.wav",
  "somersault_10": "somersault_10.wav",
  "wood_bat_finisher_01": "wood_bat_finisher_01.wav",
  "wood_bat_finisher_05": "wood_bat_finisher_05.wav"
};
