/* AUTO-GENERATED by tools/pipeline/make_hud_tiles.py -- do not edit */
#ifndef BATTLEFI_HUD_TILES_H
#define BATTLEFI_HUD_TILES_H

/* Tile numbers into BG2's tileset (res/hud_font.bmp). */

#define UI_TILE_COUNT 416
#define UI_TILES_BYTES 13312
#define UI_BIG_CHARS 38
#define UI_BAR_LEVELS 9
#define UI_BAR_TILES 12

#define UI_T_FONT          0
#define UI_T_PLATED        96
#define UI_T_BIG           192
#define UI_T_BIGP          344
#define UI_T_BAR           384
#define UI_T_PLATE         402
#define UI_T_PLATE_TOP     403
#define UI_T_PLATE_BOT     404
#define UI_T_PIP_ON        405
#define UI_T_PIP_OFF       406

/* Chip-trail segments follow the solid ones. */
#define UI_T_BAR_GHOST (UI_T_BAR + UI_BAR_LEVELS)

#endif
