import { extendMoves } from '../extendMoves.js';

// BREAKER is an invented arcade loadout, not an assessment of its avatar.
export const moves = extendMoves({
  lightPunch: { name: 'Short Fuse', startup: 5, recovery: 9,
    hit: { damage: 47, box: [0.26, 0.97, 1.24, 1.62] } },
  heavyPunch: { name: 'Bell Ringer', startup: 12, recovery: 23,
    hit: { damage: 126, chip: 11, bloodScale: 1.65, push: [0.12, 0.46] } },
  lightKick: { name: 'Kickback', startup: 6, recovery: 10 },
  heavyKick: { name: 'Last Call', startup: 15, recovery: 26,
    hit: { damage: 132, bloodScale: 1.8 } },
  grab: { name: 'Iron Clinch', grabHold: 52, hit: { hitStun: 52 } },
  throw: { name: 'Floor Is Yours', startup: 6, recovery: 32,
    hit: { damage: 165, push: [0, 1.55], bloodScale: 2.2 } },
  bodyCheck: { name: 'Door Buster', startup: 10, recovery: 20, travel: 2.3,
    hit: { damage: 83, push: [0.10, 0.35] } },
  powerStrike: { name: 'Gold Standard', startup: 22, recovery: 34,
    hit: { damage: 182, chip: 20, bloodScale: 1.85, push: [0.12, 0.8] } },
  hammerRush: { name: 'Velvet Hammer', startup: 14, recovery: 29, travel: 3.6,
    hit: { damage: 205, bloodScale: 2.1, push: [0.10, 0.7] } },
  groundBreaker: { name: 'Seismic Clause', startup: 24, recovery: 34,
    hit: { damage: 232, chip: 23, bloodScale: 2.3, box: [0.20, 1.62, 0.2, 1.7] } },
  burstStrike: { name: 'Main Event', startup: 27, recovery: 45,
    hit: { damage: 325, bloodScale: 2.9 } },
  lungePunch: { name: 'Red Carpet Rush', startup: 16, recovery: 27, travel: 3.2,
    hit: { damage: 124, bloodScale: 1.6 } },
  uppercut: { name: 'Roof Raiser', startup: 10, recovery: 27,
    hit: { damage: 132, bloodScale: 1.7 } },
  retreatKick: { name: 'Walk Away', recovery: 20, travel: -1.4 },
  heelDrop: { name: 'Foreclosure' },
  risingKnee: { name: 'Escalator' },
  meteorKick: { name: 'Penthouse Drop' },
  cyclone: { name: 'Wrecking Ball' },
  crouchPunch: { name: 'Low Bid' },
  crouchKick: { name: 'Demolition' },
  jumpAttack: { name: 'Skyline Drop' },
});
