"""Generate ROM asm + C header for streamed fighter frames.

Expects gfx4snes already produced:
  rom/res/frames/<slug>_<action>_NN.pic  (2048 bytes each)
  rom/res/frames/<slug>_idle_00.pal

Writes:
  rom/res/frames_data.as   — one superfree section per frame + bank/addr tables
  rom/src/anim_frames.h    — C externs for tables and palettes

    python tools/pipeline/generate_frame_asm.py
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FRAMES_DIR = ROOT / "rom" / "res" / "frames"
FRAME_BYTES = 2048
FIGHTERS = ("trump", "carney")
ACTIONS = ("idle", "punch", "kick", "hit")
NFRAMES = 21


def sym(slug: str, action: str, i: int) -> str:
    return f"{slug}_{action}_{i:02d}"


def main() -> None:
    missing = []
    for slug in FIGHTERS:
        for action in ACTIONS:
            for i in range(NFRAMES):
                pic = FRAMES_DIR / f"{sym(slug, action, i)}.pic"
                if not pic.exists():
                    missing.append(str(pic))
                else:
                    sz = pic.stat().st_size
                    if sz != FRAME_BYTES:
                        raise SystemExit(
                            f"{pic.name}: expected {FRAME_BYTES} bytes, got {sz}. "
                            "gfx4snes -s 32 on 64x64 must yield 2048."
                        )
    if missing:
        raise SystemExit(
            "missing .pic frames (run pack_fighter_frames.py + gfx4snes first):\n"
            + "\n".join(missing[:8])
        )

    as_lines = [
        "; AUTO-GENERATED by tools/pipeline/generate_frame_asm.py — do not edit",
        "",
    ]
    for slug in FIGHTERS:
        for action in ACTIONS:
            for i in range(NFRAMES):
                s = sym(slug, action, i)
                as_lines += [
                    f'.section "fr_{s}" superfree',
                    f"{s}:",
                    f'.incbin "res/frames/{s}.pic"',
                    f"{s}_end:",
                    ".ends",
                    "",
                ]

    as_lines += [
        '.section "anim_frame_tables" superfree',
        "",
    ]
    for slug in FIGHTERS:
        for action in ACTIONS:
            base = f"{slug}_{action}"
            as_lines.append(f"{base}_banks:")
            for i in range(NFRAMES):
                as_lines.append(f"    .db :{sym(slug, action, i)}")
            as_lines.append(f"{base}_addrs:")
            for i in range(NFRAMES):
                as_lines.append(f"    .dw {sym(slug, action, i)}")
            as_lines.append("")

        # Palette: gfx4snes writes beside the bmp; build copies idle_00.pal up
        as_lines += [
            f"{slug}_fighter_pal:",
            f'.incbin "res/frames/{slug}_idle_00.pal"',
            f"{slug}_fighter_pal_end:",
            "",
        ]

    as_lines.append(".ends")
    as_path = ROOT / "rom" / "res" / "frames_data.as"
    as_path.write_text("\n".join(as_lines) + "\n", encoding="utf-8")
    print(f"wrote {as_path.relative_to(ROOT)}")

    h_lines = [
        "/* AUTO-GENERATED by tools/pipeline/generate_frame_asm.py — do not edit */",
        "#ifndef ANIM_FRAMES_H_",
        "#define ANIM_FRAMES_H_",
        "",
        "#include <snes.h>",
        "",
        f"#define ANIM_NFRAMES {NFRAMES}",
        f"#define FRAME_BYTES {FRAME_BYTES}",
        "",
    ]
    for slug in FIGHTERS:
        for action in ACTIONS:
            h_lines.append(f"extern const u8 {slug}_{action}_banks[ANIM_NFRAMES];")
            h_lines.append(f"extern const u16 {slug}_{action}_addrs[ANIM_NFRAMES];")
        h_lines.append(f"extern char {slug}_fighter_pal, {slug}_fighter_pal_end;")
        h_lines.append("")

    h_lines += ["#endif", ""]
    h_path = ROOT / "rom" / "src" / "anim_frames.h"
    h_path.write_text("\n".join(h_lines), encoding="utf-8")
    print(f"wrote {h_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
