#!/usr/bin/env bash
set -euo pipefail

export PATH="${HOME}/local/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export PVSNESLIB_HOME="${HOME}/pvsneslib"
GFX="${PVSNESLIB_HOME}/devkitsnes/tools/gfx4snes"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SRC="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
BUILD="${HOME}/bfi-build"

echo "Syncing sources to $BUILD (no spaces) ..."
rm -rf "$BUILD"
mkdir -p "$BUILD"
cp -a "$SRC/rom" "$BUILD/rom"
cd "$BUILD/rom"

echo "PVSNESLIB_HOME=$PVSNESLIB_HOME"
make --version | head -1

FIGHTERS="trump carney"
ACTIONS="idle punch kick hit"
NFRAMES=21
FRAME_BYTES=4096

echo "=== converting animation frames (gfx4snes -s 32, 128x64 -> 4096 bytes) ==="
test -d res/frames || { echo "missing res/frames — run: python tools/pipeline/pack_fighter_frames.py"; exit 1; }
for slug in $FIGHTERS; do
  for action in $ACTIONS; do
    for i in $(seq -w 0 20); do
      f="res/frames/${slug}_${action}_${i}"
      test -f "${f}.bmp" || { echo "missing ${f}.bmp"; exit 1; }
      "$GFX" -s 32 -o 16 -u 16 -p -t bmp -i "${f}.bmp"
      sz=$(wc -c < "${f}.pic")
      # 128x64 = 8 blocks of 32x32 = 4096 bytes, no name-table padding.
      # A wrong size here uploads a fraction of each sprite and the attack
      # frames read mid-idle garbage. Measure it, never assume it.
      if [ "$sz" -ne "$FRAME_BYTES" ]; then
        echo "BAD SIZE ${f}.pic = $sz (want $FRAME_BYTES)"
        exit 1
      fi
    done
    echo "  ${slug}_${action}: 21 frames ok"
  done
done

echo "=== converting lake BG ==="
test -f res/lake.png || { echo "missing res/lake.png"; exit 1; }
"$GFX" -s 8 -o 16 -u 16 -e 0 -p -m -t png -i res/lake.png

echo "=== converting UI tileset ==="
# -R is load-bearing: the HUD tileset contains genuine duplicate tiles (blank
# quadrants of display glyphs, the plated space vs the solid plate) and tile
# reduction would renumber everything after the first collision, so every
# #define in src/hud_tiles.h would point at the wrong art. Regenerate the
# bitmap with tools/pipeline/make_hud_tiles.py, never by hand.
test -f res/hud_font.bmp || { echo "missing res/hud_font.bmp"; exit 1; }
"$GFX" -s 8 -o 16 -u 16 -e 1 -R -p -t bmp -i res/hud_font.bmp
hud_sz=$(wc -c < res/hud_font.pic)
want_hud=$(sed -n 's/^#define UI_TILES_BYTES \([0-9]*\).*/\1/p' src/hud_tiles.h)
if [ "$hud_sz" -ne "$want_hud" ]; then
  echo "BAD SIZE res/hud_font.pic = $hud_sz (src/hud_tiles.h says $want_hud)"
  exit 1
fi
echo "  hud tileset: $hud_sz bytes ok"

echo "=== generating frame asm tables ==="
# Prefer host-generated header if present; regenerate from .pic set here.
python3 <<'PY'
from pathlib import Path

FRAMES_DIR = Path("res/frames")
FRAME_BYTES = 4096
FIGHTERS = ("trump", "carney")
ACTIONS = ("idle", "punch", "kick", "hit")
NFRAMES = 21

def sym(slug, action, i):
    return f"{slug}_{action}_{i:02d}"

for slug in FIGHTERS:
    for action in ACTIONS:
        for i in range(NFRAMES):
            pic = FRAMES_DIR / f"{sym(slug, action, i)}.pic"
            sz = pic.stat().st_size
            if sz != FRAME_BYTES:
                raise SystemExit(f"{pic}: {sz} bytes, want {FRAME_BYTES}")

as_lines = ["; AUTO-GENERATED by wsl_build_rom.sh", ""]
for slug in FIGHTERS:
    for action in ACTIONS:
        for i in range(NFRAMES):
            s = sym(slug, action, i)
            as_lines += [
                f'.section "fr_{s}" superfree',
                f"{s}:",
                f'.incbin "res/frames/{s}.pic"',
                f"{s}_end:",
                ".ends",
                "",
            ]

as_lines += ['.section "anim_frame_tables" superfree', ""]
for slug in FIGHTERS:
    for action in ACTIONS:
        base = f"{slug}_{action}"
        as_lines.append(f"{base}_banks:")
        for i in range(NFRAMES):
            as_lines.append(f"    .db :{sym(slug, action, i)}")
        as_lines.append(f"{base}_addrs:")
        for i in range(NFRAMES):
            as_lines.append(f"    .dw {sym(slug, action, i)}")
        as_lines.append("")
    as_lines += [
        f"{slug}_fighter_pal:",
        f'.incbin "res/frames/{slug}_idle_00.pal"',
        f"{slug}_fighter_pal_end:",
        "",
    ]
as_lines.append(".ends")
Path("res/frames_data.as").write_text("\n".join(as_lines) + "\n")
print("wrote res/frames_data.as")

h_lines = [
    "/* AUTO-GENERATED — do not edit */",
    "#ifndef ANIM_FRAMES_H_",
    "#define ANIM_FRAMES_H_",
    "",
    "#include <snes.h>",
    "",
    f"#define ANIM_NFRAMES {NFRAMES}",
    f"#define FRAME_BYTES {FRAME_BYTES}",
    "",
]
for slug in FIGHTERS:
    for action in ACTIONS:
        h_lines.append(f"extern const u8 {slug}_{action}_banks[ANIM_NFRAMES];")
        h_lines.append(f"extern const u16 {slug}_{action}_addrs[ANIM_NFRAMES];")
    h_lines.append(f"extern char {slug}_fighter_pal, {slug}_fighter_pal_end;")
    h_lines.append("")
h_lines += ["#endif", ""]
Path("src/anim_frames.h").write_text("\n".join(h_lines))
print("wrote src/anim_frames.h")
PY

python3 - <<'PY'
from pathlib import Path
import re
nbytes = Path("res/lake.pic").stat().st_size
print("LAKE_TILE_BYTES", nbytes)
main = Path("src/main.c").read_text()
main = re.sub(r"#define LAKE_TILE_BYTES \d+", f"#define LAKE_TILE_BYTES {nbytes}", main)
Path("src/main.c").write_text(main)
PY

rm -f src/*.obj src/*.ps src/*.asm data.obj hdr.obj battlefi.sfc battlefi.sym battlefi.symfull linkfile

make src/main.obj data.obj hdr.obj
make battlefi.sfc

ls -la battlefi.sfc
cp -f battlefi.sfc "$SRC/battlefi.sfc"
cp -f battlefi.sfc "$SRC/rom/battlefi.sfc"
# Copy generated header back so the Windows tree stays in sync
cp -f src/anim_frames.h "$SRC/rom/src/anim_frames.h"
cp -f res/frames_data.as "$SRC/rom/res/frames_data.as"
echo "Built and copied to battle for independance/battlefi.sfc"
