import { extendMoves } from '../extendMoves.js';

// STRIDER is an invented arcade loadout, not an assessment of its avatar.
const baseMoves = extendMoves({
  lightPunch: { name: 'Quick Edit', startup: 3, recovery: 6,
    cancelInto: ['heavyPunch', 'lightKick', 'heavyKick', 'grab', 'lungePunch', 'bodyCheck'],
    cancelWindow: [3, 11],
    hit: { damage: 35, hitStun: 17, push: [0.05, 0.10], box: [0.26, 1.08, 1.24, 1.62] } },
  heavyPunch: { name: 'Clean Break', startup: 8, recovery: 16,
    hit: { damage: 85, box: [0.28, 1.40, 1.10, 1.74] } },
  lightKick: { name: 'Cold Open', startup: 4, recovery: 7,
    cancelInto: ['heavyKick', 'heavyPunch', 'throw', 'heelDrop'], cancelWindow: [4, 13],
    hit: { damage: 41, hitStun: 21, push: [0.04, 0.10], box: [0.26, 1.20, 0.62, 1.06] } },
  heavyKick: { name: 'Final Draft', startup: 10, recovery: 19,
    hit: { damage: 101, box: [0.28, 1.57, 1.15, 1.92] } },
  bodyCheck: { name: 'Second Reading', startup: 5, recovery: 18, travel: 2.2,
    cancelInto: ['heavyKick', 'risingKnee', 'spinKick'], cancelWindow: [5, 14],
    hit: { damage: 48, hitStun: 22, push: [0.03, 0.10] } },
  grab: { name: 'Closed Session' },
  throw: { name: 'Table Flip', startup: 4, recovery: 27,
    hit: { damage: 117, push: [0, 1.2] } },
  powerStrike: { name: 'Rate Hike' },
  hammerRush: { name: 'Breakaway' },
  groundBreaker: { name: 'Hard Freeze' },
  uppercut: { name: 'Upward Revision' },
  crouchPunch: { name: 'Footnote' },
  jumpAttack: { name: 'Blue Line Dive' },
  heelDrop: { name: 'Ice Pick', startup: 13, recovery: 20,
    hit: { damage: 94, box: [0.25, 1.54, 1.05, 1.9] } },
  risingKnee: { name: 'Cold Shoulder', startup: 7, recovery: 18, travel: 1.1,
    hit: { damage: 82, hitStun: 27 } },
  meteorKick: { name: 'Phantom Slapshot', clip: 'heavyPunch', weapon: 'hockey', startup: 22, recovery: 30,
    description: 'Summon an independent hockey-stick swing. An overhead: block standing. Punishable on a miss.',
    hit: { damage: 166, box: [0.2, 1.68, 0.9, 1.98], bloodScale: 1.7 } },
  cyclone: { name: 'Slush Pile', startup: 10, recovery: 22, travel: 2.2,
    hit: { damage: 148, box: [0.18, 1.8, 0.08, 0.65] } },
  burstStrike: { name: 'Absolute Zero', startup: 18, recovery: 34,
    hit: { damage: 255, box: [0.18, 1.9, 0.4, 1.95], bloodScale: 2.3 } },
  lungePunch: { name: 'Slipstream', startup: 10, recovery: 20, travel: 3.6,
    hit: { damage: 88, box: [0.22, 1.62, 1.1, 1.76] } },
  retreatKick: { name: 'Out of Office', startup: 6, recovery: 13, travel: -2.5,
    hit: { damage: 54, box: [0.24, 1.52, 0.6, 1.2] } },
  crouchKick: { name: 'Black Ice', startup: 7, recovery: 17,
    hit: { damage: 63, box: [0.24, 1.47, 0.06, 0.5] } },
});

// A kit-only move is registered explicitly: extendMoves only overrides universal IDs.
export const moves = Object.freeze({ ...baseMoves,
  spinKick: Object.freeze({ ...baseMoves.heavyKick, id: 'spinKick', name: 'Polar Reversal',
    clip: 'spinKick', startup: 14, active: 5, recovery: 27, cost: 1, travel: 1.4,
    description: 'Forward + HK. A full-turn heel strike, or LP, LP, HK after landing the opener. Costs one stock; a miss leaves a long opening.',
    hit: Object.freeze({ ...baseMoves.heavyKick.hit, damage: 148,
      box: Object.freeze([0.25, 1.65, 0.95, 1.80]), push: Object.freeze([0.1, 0.9]), hitStop: 11, meter: 12, bloodScale: 1.9 }),
  }),
});
