; AUTO-GENERATED by wsl_build_rom.sh

.section "fr_trump_idle_00" superfree
trump_idle_00:
.incbin "res/frames/trump_idle_00.pic"
trump_idle_00_end:
.ends

.section "fr_trump_idle_01" superfree
trump_idle_01:
.incbin "res/frames/trump_idle_01.pic"
trump_idle_01_end:
.ends

.section "fr_trump_idle_02" superfree
trump_idle_02:
.incbin "res/frames/trump_idle_02.pic"
trump_idle_02_end:
.ends

.section "fr_trump_idle_03" superfree
trump_idle_03:
.incbin "res/frames/trump_idle_03.pic"
trump_idle_03_end:
.ends

.section "fr_trump_idle_04" superfree
trump_idle_04:
.incbin "res/frames/trump_idle_04.pic"
trump_idle_04_end:
.ends

.section "fr_trump_idle_05" superfree
trump_idle_05:
.incbin "res/frames/trump_idle_05.pic"
trump_idle_05_end:
.ends

.section "fr_trump_idle_06" superfree
trump_idle_06:
.incbin "res/frames/trump_idle_06.pic"
trump_idle_06_end:
.ends

.section "fr_trump_idle_07" superfree
trump_idle_07:
.incbin "res/frames/trump_idle_07.pic"
trump_idle_07_end:
.ends

.section "fr_trump_idle_08" superfree
trump_idle_08:
.incbin "res/frames/trump_idle_08.pic"
trump_idle_08_end:
.ends

.section "fr_trump_idle_09" superfree
trump_idle_09:
.incbin "res/frames/trump_idle_09.pic"
trump_idle_09_end:
.ends

.section "fr_trump_idle_10" superfree
trump_idle_10:
.incbin "res/frames/trump_idle_10.pic"
trump_idle_10_end:
.ends

.section "fr_trump_idle_11" superfree
trump_idle_11:
.incbin "res/frames/trump_idle_11.pic"
trump_idle_11_end:
.ends

.section "fr_trump_idle_12" superfree
trump_idle_12:
.incbin "res/frames/trump_idle_12.pic"
trump_idle_12_end:
.ends

.section "fr_trump_idle_13" superfree
trump_idle_13:
.incbin "res/frames/trump_idle_13.pic"
trump_idle_13_end:
.ends

.section "fr_trump_idle_14" superfree
trump_idle_14:
.incbin "res/frames/trump_idle_14.pic"
trump_idle_14_end:
.ends

.section "fr_trump_idle_15" superfree
trump_idle_15:
.incbin "res/frames/trump_idle_15.pic"
trump_idle_15_end:
.ends

.section "fr_trump_idle_16" superfree
trump_idle_16:
.incbin "res/frames/trump_idle_16.pic"
trump_idle_16_end:
.ends

.section "fr_trump_idle_17" superfree
trump_idle_17:
.incbin "res/frames/trump_idle_17.pic"
trump_idle_17_end:
.ends

.section "fr_trump_idle_18" superfree
trump_idle_18:
.incbin "res/frames/trump_idle_18.pic"
trump_idle_18_end:
.ends

.section "fr_trump_idle_19" superfree
trump_idle_19:
.incbin "res/frames/trump_idle_19.pic"
trump_idle_19_end:
.ends

.section "fr_trump_idle_20" superfree
trump_idle_20:
.incbin "res/frames/trump_idle_20.pic"
trump_idle_20_end:
.ends

.section "fr_trump_punch_00" superfree
trump_punch_00:
.incbin "res/frames/trump_punch_00.pic"
trump_punch_00_end:
.ends

.section "fr_trump_punch_01" superfree
trump_punch_01:
.incbin "res/frames/trump_punch_01.pic"
trump_punch_01_end:
.ends

.section "fr_trump_punch_02" superfree
trump_punch_02:
.incbin "res/frames/trump_punch_02.pic"
trump_punch_02_end:
.ends

.section "fr_trump_punch_03" superfree
trump_punch_03:
.incbin "res/frames/trump_punch_03.pic"
trump_punch_03_end:
.ends

.section "fr_trump_punch_04" superfree
trump_punch_04:
.incbin "res/frames/trump_punch_04.pic"
trump_punch_04_end:
.ends

.section "fr_trump_punch_05" superfree
trump_punch_05:
.incbin "res/frames/trump_punch_05.pic"
trump_punch_05_end:
.ends

.section "fr_trump_punch_06" superfree
trump_punch_06:
.incbin "res/frames/trump_punch_06.pic"
trump_punch_06_end:
.ends

.section "fr_trump_punch_07" superfree
trump_punch_07:
.incbin "res/frames/trump_punch_07.pic"
trump_punch_07_end:
.ends

.section "fr_trump_punch_08" superfree
trump_punch_08:
.incbin "res/frames/trump_punch_08.pic"
trump_punch_08_end:
.ends

.section "fr_trump_punch_09" superfree
trump_punch_09:
.incbin "res/frames/trump_punch_09.pic"
trump_punch_09_end:
.ends

.section "fr_trump_punch_10" superfree
trump_punch_10:
.incbin "res/frames/trump_punch_10.pic"
trump_punch_10_end:
.ends

.section "fr_trump_punch_11" superfree
trump_punch_11:
.incbin "res/frames/trump_punch_11.pic"
trump_punch_11_end:
.ends

.section "fr_trump_punch_12" superfree
trump_punch_12:
.incbin "res/frames/trump_punch_12.pic"
trump_punch_12_end:
.ends

.section "fr_trump_punch_13" superfree
trump_punch_13:
.incbin "res/frames/trump_punch_13.pic"
trump_punch_13_end:
.ends

.section "fr_trump_punch_14" superfree
trump_punch_14:
.incbin "res/frames/trump_punch_14.pic"
trump_punch_14_end:
.ends

.section "fr_trump_punch_15" superfree
trump_punch_15:
.incbin "res/frames/trump_punch_15.pic"
trump_punch_15_end:
.ends

.section "fr_trump_punch_16" superfree
trump_punch_16:
.incbin "res/frames/trump_punch_16.pic"
trump_punch_16_end:
.ends

.section "fr_trump_punch_17" superfree
trump_punch_17:
.incbin "res/frames/trump_punch_17.pic"
trump_punch_17_end:
.ends

.section "fr_trump_punch_18" superfree
trump_punch_18:
.incbin "res/frames/trump_punch_18.pic"
trump_punch_18_end:
.ends

.section "fr_trump_punch_19" superfree
trump_punch_19:
.incbin "res/frames/trump_punch_19.pic"
trump_punch_19_end:
.ends

.section "fr_trump_punch_20" superfree
trump_punch_20:
.incbin "res/frames/trump_punch_20.pic"
trump_punch_20_end:
.ends

.section "fr_trump_kick_00" superfree
trump_kick_00:
.incbin "res/frames/trump_kick_00.pic"
trump_kick_00_end:
.ends

.section "fr_trump_kick_01" superfree
trump_kick_01:
.incbin "res/frames/trump_kick_01.pic"
trump_kick_01_end:
.ends

.section "fr_trump_kick_02" superfree
trump_kick_02:
.incbin "res/frames/trump_kick_02.pic"
trump_kick_02_end:
.ends

.section "fr_trump_kick_03" superfree
trump_kick_03:
.incbin "res/frames/trump_kick_03.pic"
trump_kick_03_end:
.ends

.section "fr_trump_kick_04" superfree
trump_kick_04:
.incbin "res/frames/trump_kick_04.pic"
trump_kick_04_end:
.ends

.section "fr_trump_kick_05" superfree
trump_kick_05:
.incbin "res/frames/trump_kick_05.pic"
trump_kick_05_end:
.ends

.section "fr_trump_kick_06" superfree
trump_kick_06:
.incbin "res/frames/trump_kick_06.pic"
trump_kick_06_end:
.ends

.section "fr_trump_kick_07" superfree
trump_kick_07:
.incbin "res/frames/trump_kick_07.pic"
trump_kick_07_end:
.ends

.section "fr_trump_kick_08" superfree
trump_kick_08:
.incbin "res/frames/trump_kick_08.pic"
trump_kick_08_end:
.ends

.section "fr_trump_kick_09" superfree
trump_kick_09:
.incbin "res/frames/trump_kick_09.pic"
trump_kick_09_end:
.ends

.section "fr_trump_kick_10" superfree
trump_kick_10:
.incbin "res/frames/trump_kick_10.pic"
trump_kick_10_end:
.ends

.section "fr_trump_kick_11" superfree
trump_kick_11:
.incbin "res/frames/trump_kick_11.pic"
trump_kick_11_end:
.ends

.section "fr_trump_kick_12" superfree
trump_kick_12:
.incbin "res/frames/trump_kick_12.pic"
trump_kick_12_end:
.ends

.section "fr_trump_kick_13" superfree
trump_kick_13:
.incbin "res/frames/trump_kick_13.pic"
trump_kick_13_end:
.ends

.section "fr_trump_kick_14" superfree
trump_kick_14:
.incbin "res/frames/trump_kick_14.pic"
trump_kick_14_end:
.ends

.section "fr_trump_kick_15" superfree
trump_kick_15:
.incbin "res/frames/trump_kick_15.pic"
trump_kick_15_end:
.ends

.section "fr_trump_kick_16" superfree
trump_kick_16:
.incbin "res/frames/trump_kick_16.pic"
trump_kick_16_end:
.ends

.section "fr_trump_kick_17" superfree
trump_kick_17:
.incbin "res/frames/trump_kick_17.pic"
trump_kick_17_end:
.ends

.section "fr_trump_kick_18" superfree
trump_kick_18:
.incbin "res/frames/trump_kick_18.pic"
trump_kick_18_end:
.ends

.section "fr_trump_kick_19" superfree
trump_kick_19:
.incbin "res/frames/trump_kick_19.pic"
trump_kick_19_end:
.ends

.section "fr_trump_kick_20" superfree
trump_kick_20:
.incbin "res/frames/trump_kick_20.pic"
trump_kick_20_end:
.ends

.section "fr_trump_hit_00" superfree
trump_hit_00:
.incbin "res/frames/trump_hit_00.pic"
trump_hit_00_end:
.ends

.section "fr_trump_hit_01" superfree
trump_hit_01:
.incbin "res/frames/trump_hit_01.pic"
trump_hit_01_end:
.ends

.section "fr_trump_hit_02" superfree
trump_hit_02:
.incbin "res/frames/trump_hit_02.pic"
trump_hit_02_end:
.ends

.section "fr_trump_hit_03" superfree
trump_hit_03:
.incbin "res/frames/trump_hit_03.pic"
trump_hit_03_end:
.ends

.section "fr_trump_hit_04" superfree
trump_hit_04:
.incbin "res/frames/trump_hit_04.pic"
trump_hit_04_end:
.ends

.section "fr_trump_hit_05" superfree
trump_hit_05:
.incbin "res/frames/trump_hit_05.pic"
trump_hit_05_end:
.ends

.section "fr_trump_hit_06" superfree
trump_hit_06:
.incbin "res/frames/trump_hit_06.pic"
trump_hit_06_end:
.ends

.section "fr_trump_hit_07" superfree
trump_hit_07:
.incbin "res/frames/trump_hit_07.pic"
trump_hit_07_end:
.ends

.section "fr_trump_hit_08" superfree
trump_hit_08:
.incbin "res/frames/trump_hit_08.pic"
trump_hit_08_end:
.ends

.section "fr_trump_hit_09" superfree
trump_hit_09:
.incbin "res/frames/trump_hit_09.pic"
trump_hit_09_end:
.ends

.section "fr_trump_hit_10" superfree
trump_hit_10:
.incbin "res/frames/trump_hit_10.pic"
trump_hit_10_end:
.ends

.section "fr_trump_hit_11" superfree
trump_hit_11:
.incbin "res/frames/trump_hit_11.pic"
trump_hit_11_end:
.ends

.section "fr_trump_hit_12" superfree
trump_hit_12:
.incbin "res/frames/trump_hit_12.pic"
trump_hit_12_end:
.ends

.section "fr_trump_hit_13" superfree
trump_hit_13:
.incbin "res/frames/trump_hit_13.pic"
trump_hit_13_end:
.ends

.section "fr_trump_hit_14" superfree
trump_hit_14:
.incbin "res/frames/trump_hit_14.pic"
trump_hit_14_end:
.ends

.section "fr_trump_hit_15" superfree
trump_hit_15:
.incbin "res/frames/trump_hit_15.pic"
trump_hit_15_end:
.ends

.section "fr_trump_hit_16" superfree
trump_hit_16:
.incbin "res/frames/trump_hit_16.pic"
trump_hit_16_end:
.ends

.section "fr_trump_hit_17" superfree
trump_hit_17:
.incbin "res/frames/trump_hit_17.pic"
trump_hit_17_end:
.ends

.section "fr_trump_hit_18" superfree
trump_hit_18:
.incbin "res/frames/trump_hit_18.pic"
trump_hit_18_end:
.ends

.section "fr_trump_hit_19" superfree
trump_hit_19:
.incbin "res/frames/trump_hit_19.pic"
trump_hit_19_end:
.ends

.section "fr_trump_hit_20" superfree
trump_hit_20:
.incbin "res/frames/trump_hit_20.pic"
trump_hit_20_end:
.ends

.section "fr_carney_idle_00" superfree
carney_idle_00:
.incbin "res/frames/carney_idle_00.pic"
carney_idle_00_end:
.ends

.section "fr_carney_idle_01" superfree
carney_idle_01:
.incbin "res/frames/carney_idle_01.pic"
carney_idle_01_end:
.ends

.section "fr_carney_idle_02" superfree
carney_idle_02:
.incbin "res/frames/carney_idle_02.pic"
carney_idle_02_end:
.ends

.section "fr_carney_idle_03" superfree
carney_idle_03:
.incbin "res/frames/carney_idle_03.pic"
carney_idle_03_end:
.ends

.section "fr_carney_idle_04" superfree
carney_idle_04:
.incbin "res/frames/carney_idle_04.pic"
carney_idle_04_end:
.ends

.section "fr_carney_idle_05" superfree
carney_idle_05:
.incbin "res/frames/carney_idle_05.pic"
carney_idle_05_end:
.ends

.section "fr_carney_idle_06" superfree
carney_idle_06:
.incbin "res/frames/carney_idle_06.pic"
carney_idle_06_end:
.ends

.section "fr_carney_idle_07" superfree
carney_idle_07:
.incbin "res/frames/carney_idle_07.pic"
carney_idle_07_end:
.ends

.section "fr_carney_idle_08" superfree
carney_idle_08:
.incbin "res/frames/carney_idle_08.pic"
carney_idle_08_end:
.ends

.section "fr_carney_idle_09" superfree
carney_idle_09:
.incbin "res/frames/carney_idle_09.pic"
carney_idle_09_end:
.ends

.section "fr_carney_idle_10" superfree
carney_idle_10:
.incbin "res/frames/carney_idle_10.pic"
carney_idle_10_end:
.ends

.section "fr_carney_idle_11" superfree
carney_idle_11:
.incbin "res/frames/carney_idle_11.pic"
carney_idle_11_end:
.ends

.section "fr_carney_idle_12" superfree
carney_idle_12:
.incbin "res/frames/carney_idle_12.pic"
carney_idle_12_end:
.ends

.section "fr_carney_idle_13" superfree
carney_idle_13:
.incbin "res/frames/carney_idle_13.pic"
carney_idle_13_end:
.ends

.section "fr_carney_idle_14" superfree
carney_idle_14:
.incbin "res/frames/carney_idle_14.pic"
carney_idle_14_end:
.ends

.section "fr_carney_idle_15" superfree
carney_idle_15:
.incbin "res/frames/carney_idle_15.pic"
carney_idle_15_end:
.ends

.section "fr_carney_idle_16" superfree
carney_idle_16:
.incbin "res/frames/carney_idle_16.pic"
carney_idle_16_end:
.ends

.section "fr_carney_idle_17" superfree
carney_idle_17:
.incbin "res/frames/carney_idle_17.pic"
carney_idle_17_end:
.ends

.section "fr_carney_idle_18" superfree
carney_idle_18:
.incbin "res/frames/carney_idle_18.pic"
carney_idle_18_end:
.ends

.section "fr_carney_idle_19" superfree
carney_idle_19:
.incbin "res/frames/carney_idle_19.pic"
carney_idle_19_end:
.ends

.section "fr_carney_idle_20" superfree
carney_idle_20:
.incbin "res/frames/carney_idle_20.pic"
carney_idle_20_end:
.ends

.section "fr_carney_punch_00" superfree
carney_punch_00:
.incbin "res/frames/carney_punch_00.pic"
carney_punch_00_end:
.ends

.section "fr_carney_punch_01" superfree
carney_punch_01:
.incbin "res/frames/carney_punch_01.pic"
carney_punch_01_end:
.ends

.section "fr_carney_punch_02" superfree
carney_punch_02:
.incbin "res/frames/carney_punch_02.pic"
carney_punch_02_end:
.ends

.section "fr_carney_punch_03" superfree
carney_punch_03:
.incbin "res/frames/carney_punch_03.pic"
carney_punch_03_end:
.ends

.section "fr_carney_punch_04" superfree
carney_punch_04:
.incbin "res/frames/carney_punch_04.pic"
carney_punch_04_end:
.ends

.section "fr_carney_punch_05" superfree
carney_punch_05:
.incbin "res/frames/carney_punch_05.pic"
carney_punch_05_end:
.ends

.section "fr_carney_punch_06" superfree
carney_punch_06:
.incbin "res/frames/carney_punch_06.pic"
carney_punch_06_end:
.ends

.section "fr_carney_punch_07" superfree
carney_punch_07:
.incbin "res/frames/carney_punch_07.pic"
carney_punch_07_end:
.ends

.section "fr_carney_punch_08" superfree
carney_punch_08:
.incbin "res/frames/carney_punch_08.pic"
carney_punch_08_end:
.ends

.section "fr_carney_punch_09" superfree
carney_punch_09:
.incbin "res/frames/carney_punch_09.pic"
carney_punch_09_end:
.ends

.section "fr_carney_punch_10" superfree
carney_punch_10:
.incbin "res/frames/carney_punch_10.pic"
carney_punch_10_end:
.ends

.section "fr_carney_punch_11" superfree
carney_punch_11:
.incbin "res/frames/carney_punch_11.pic"
carney_punch_11_end:
.ends

.section "fr_carney_punch_12" superfree
carney_punch_12:
.incbin "res/frames/carney_punch_12.pic"
carney_punch_12_end:
.ends

.section "fr_carney_punch_13" superfree
carney_punch_13:
.incbin "res/frames/carney_punch_13.pic"
carney_punch_13_end:
.ends

.section "fr_carney_punch_14" superfree
carney_punch_14:
.incbin "res/frames/carney_punch_14.pic"
carney_punch_14_end:
.ends

.section "fr_carney_punch_15" superfree
carney_punch_15:
.incbin "res/frames/carney_punch_15.pic"
carney_punch_15_end:
.ends

.section "fr_carney_punch_16" superfree
carney_punch_16:
.incbin "res/frames/carney_punch_16.pic"
carney_punch_16_end:
.ends

.section "fr_carney_punch_17" superfree
carney_punch_17:
.incbin "res/frames/carney_punch_17.pic"
carney_punch_17_end:
.ends

.section "fr_carney_punch_18" superfree
carney_punch_18:
.incbin "res/frames/carney_punch_18.pic"
carney_punch_18_end:
.ends

.section "fr_carney_punch_19" superfree
carney_punch_19:
.incbin "res/frames/carney_punch_19.pic"
carney_punch_19_end:
.ends

.section "fr_carney_punch_20" superfree
carney_punch_20:
.incbin "res/frames/carney_punch_20.pic"
carney_punch_20_end:
.ends

.section "fr_carney_kick_00" superfree
carney_kick_00:
.incbin "res/frames/carney_kick_00.pic"
carney_kick_00_end:
.ends

.section "fr_carney_kick_01" superfree
carney_kick_01:
.incbin "res/frames/carney_kick_01.pic"
carney_kick_01_end:
.ends

.section "fr_carney_kick_02" superfree
carney_kick_02:
.incbin "res/frames/carney_kick_02.pic"
carney_kick_02_end:
.ends

.section "fr_carney_kick_03" superfree
carney_kick_03:
.incbin "res/frames/carney_kick_03.pic"
carney_kick_03_end:
.ends

.section "fr_carney_kick_04" superfree
carney_kick_04:
.incbin "res/frames/carney_kick_04.pic"
carney_kick_04_end:
.ends

.section "fr_carney_kick_05" superfree
carney_kick_05:
.incbin "res/frames/carney_kick_05.pic"
carney_kick_05_end:
.ends

.section "fr_carney_kick_06" superfree
carney_kick_06:
.incbin "res/frames/carney_kick_06.pic"
carney_kick_06_end:
.ends

.section "fr_carney_kick_07" superfree
carney_kick_07:
.incbin "res/frames/carney_kick_07.pic"
carney_kick_07_end:
.ends

.section "fr_carney_kick_08" superfree
carney_kick_08:
.incbin "res/frames/carney_kick_08.pic"
carney_kick_08_end:
.ends

.section "fr_carney_kick_09" superfree
carney_kick_09:
.incbin "res/frames/carney_kick_09.pic"
carney_kick_09_end:
.ends

.section "fr_carney_kick_10" superfree
carney_kick_10:
.incbin "res/frames/carney_kick_10.pic"
carney_kick_10_end:
.ends

.section "fr_carney_kick_11" superfree
carney_kick_11:
.incbin "res/frames/carney_kick_11.pic"
carney_kick_11_end:
.ends

.section "fr_carney_kick_12" superfree
carney_kick_12:
.incbin "res/frames/carney_kick_12.pic"
carney_kick_12_end:
.ends

.section "fr_carney_kick_13" superfree
carney_kick_13:
.incbin "res/frames/carney_kick_13.pic"
carney_kick_13_end:
.ends

.section "fr_carney_kick_14" superfree
carney_kick_14:
.incbin "res/frames/carney_kick_14.pic"
carney_kick_14_end:
.ends

.section "fr_carney_kick_15" superfree
carney_kick_15:
.incbin "res/frames/carney_kick_15.pic"
carney_kick_15_end:
.ends

.section "fr_carney_kick_16" superfree
carney_kick_16:
.incbin "res/frames/carney_kick_16.pic"
carney_kick_16_end:
.ends

.section "fr_carney_kick_17" superfree
carney_kick_17:
.incbin "res/frames/carney_kick_17.pic"
carney_kick_17_end:
.ends

.section "fr_carney_kick_18" superfree
carney_kick_18:
.incbin "res/frames/carney_kick_18.pic"
carney_kick_18_end:
.ends

.section "fr_carney_kick_19" superfree
carney_kick_19:
.incbin "res/frames/carney_kick_19.pic"
carney_kick_19_end:
.ends

.section "fr_carney_kick_20" superfree
carney_kick_20:
.incbin "res/frames/carney_kick_20.pic"
carney_kick_20_end:
.ends

.section "fr_carney_hit_00" superfree
carney_hit_00:
.incbin "res/frames/carney_hit_00.pic"
carney_hit_00_end:
.ends

.section "fr_carney_hit_01" superfree
carney_hit_01:
.incbin "res/frames/carney_hit_01.pic"
carney_hit_01_end:
.ends

.section "fr_carney_hit_02" superfree
carney_hit_02:
.incbin "res/frames/carney_hit_02.pic"
carney_hit_02_end:
.ends

.section "fr_carney_hit_03" superfree
carney_hit_03:
.incbin "res/frames/carney_hit_03.pic"
carney_hit_03_end:
.ends

.section "fr_carney_hit_04" superfree
carney_hit_04:
.incbin "res/frames/carney_hit_04.pic"
carney_hit_04_end:
.ends

.section "fr_carney_hit_05" superfree
carney_hit_05:
.incbin "res/frames/carney_hit_05.pic"
carney_hit_05_end:
.ends

.section "fr_carney_hit_06" superfree
carney_hit_06:
.incbin "res/frames/carney_hit_06.pic"
carney_hit_06_end:
.ends

.section "fr_carney_hit_07" superfree
carney_hit_07:
.incbin "res/frames/carney_hit_07.pic"
carney_hit_07_end:
.ends

.section "fr_carney_hit_08" superfree
carney_hit_08:
.incbin "res/frames/carney_hit_08.pic"
carney_hit_08_end:
.ends

.section "fr_carney_hit_09" superfree
carney_hit_09:
.incbin "res/frames/carney_hit_09.pic"
carney_hit_09_end:
.ends

.section "fr_carney_hit_10" superfree
carney_hit_10:
.incbin "res/frames/carney_hit_10.pic"
carney_hit_10_end:
.ends

.section "fr_carney_hit_11" superfree
carney_hit_11:
.incbin "res/frames/carney_hit_11.pic"
carney_hit_11_end:
.ends

.section "fr_carney_hit_12" superfree
carney_hit_12:
.incbin "res/frames/carney_hit_12.pic"
carney_hit_12_end:
.ends

.section "fr_carney_hit_13" superfree
carney_hit_13:
.incbin "res/frames/carney_hit_13.pic"
carney_hit_13_end:
.ends

.section "fr_carney_hit_14" superfree
carney_hit_14:
.incbin "res/frames/carney_hit_14.pic"
carney_hit_14_end:
.ends

.section "fr_carney_hit_15" superfree
carney_hit_15:
.incbin "res/frames/carney_hit_15.pic"
carney_hit_15_end:
.ends

.section "fr_carney_hit_16" superfree
carney_hit_16:
.incbin "res/frames/carney_hit_16.pic"
carney_hit_16_end:
.ends

.section "fr_carney_hit_17" superfree
carney_hit_17:
.incbin "res/frames/carney_hit_17.pic"
carney_hit_17_end:
.ends

.section "fr_carney_hit_18" superfree
carney_hit_18:
.incbin "res/frames/carney_hit_18.pic"
carney_hit_18_end:
.ends

.section "fr_carney_hit_19" superfree
carney_hit_19:
.incbin "res/frames/carney_hit_19.pic"
carney_hit_19_end:
.ends

.section "fr_carney_hit_20" superfree
carney_hit_20:
.incbin "res/frames/carney_hit_20.pic"
carney_hit_20_end:
.ends

.section "anim_frame_tables" superfree

trump_idle_banks:
    .db :trump_idle_00
    .db :trump_idle_01
    .db :trump_idle_02
    .db :trump_idle_03
    .db :trump_idle_04
    .db :trump_idle_05
    .db :trump_idle_06
    .db :trump_idle_07
    .db :trump_idle_08
    .db :trump_idle_09
    .db :trump_idle_10
    .db :trump_idle_11
    .db :trump_idle_12
    .db :trump_idle_13
    .db :trump_idle_14
    .db :trump_idle_15
    .db :trump_idle_16
    .db :trump_idle_17
    .db :trump_idle_18
    .db :trump_idle_19
    .db :trump_idle_20
trump_idle_addrs:
    .dw trump_idle_00
    .dw trump_idle_01
    .dw trump_idle_02
    .dw trump_idle_03
    .dw trump_idle_04
    .dw trump_idle_05
    .dw trump_idle_06
    .dw trump_idle_07
    .dw trump_idle_08
    .dw trump_idle_09
    .dw trump_idle_10
    .dw trump_idle_11
    .dw trump_idle_12
    .dw trump_idle_13
    .dw trump_idle_14
    .dw trump_idle_15
    .dw trump_idle_16
    .dw trump_idle_17
    .dw trump_idle_18
    .dw trump_idle_19
    .dw trump_idle_20

trump_punch_banks:
    .db :trump_punch_00
    .db :trump_punch_01
    .db :trump_punch_02
    .db :trump_punch_03
    .db :trump_punch_04
    .db :trump_punch_05
    .db :trump_punch_06
    .db :trump_punch_07
    .db :trump_punch_08
    .db :trump_punch_09
    .db :trump_punch_10
    .db :trump_punch_11
    .db :trump_punch_12
    .db :trump_punch_13
    .db :trump_punch_14
    .db :trump_punch_15
    .db :trump_punch_16
    .db :trump_punch_17
    .db :trump_punch_18
    .db :trump_punch_19
    .db :trump_punch_20
trump_punch_addrs:
    .dw trump_punch_00
    .dw trump_punch_01
    .dw trump_punch_02
    .dw trump_punch_03
    .dw trump_punch_04
    .dw trump_punch_05
    .dw trump_punch_06
    .dw trump_punch_07
    .dw trump_punch_08
    .dw trump_punch_09
    .dw trump_punch_10
    .dw trump_punch_11
    .dw trump_punch_12
    .dw trump_punch_13
    .dw trump_punch_14
    .dw trump_punch_15
    .dw trump_punch_16
    .dw trump_punch_17
    .dw trump_punch_18
    .dw trump_punch_19
    .dw trump_punch_20

trump_kick_banks:
    .db :trump_kick_00
    .db :trump_kick_01
    .db :trump_kick_02
    .db :trump_kick_03
    .db :trump_kick_04
    .db :trump_kick_05
    .db :trump_kick_06
    .db :trump_kick_07
    .db :trump_kick_08
    .db :trump_kick_09
    .db :trump_kick_10
    .db :trump_kick_11
    .db :trump_kick_12
    .db :trump_kick_13
    .db :trump_kick_14
    .db :trump_kick_15
    .db :trump_kick_16
    .db :trump_kick_17
    .db :trump_kick_18
    .db :trump_kick_19
    .db :trump_kick_20
trump_kick_addrs:
    .dw trump_kick_00
    .dw trump_kick_01
    .dw trump_kick_02
    .dw trump_kick_03
    .dw trump_kick_04
    .dw trump_kick_05
    .dw trump_kick_06
    .dw trump_kick_07
    .dw trump_kick_08
    .dw trump_kick_09
    .dw trump_kick_10
    .dw trump_kick_11
    .dw trump_kick_12
    .dw trump_kick_13
    .dw trump_kick_14
    .dw trump_kick_15
    .dw trump_kick_16
    .dw trump_kick_17
    .dw trump_kick_18
    .dw trump_kick_19
    .dw trump_kick_20

trump_hit_banks:
    .db :trump_hit_00
    .db :trump_hit_01
    .db :trump_hit_02
    .db :trump_hit_03
    .db :trump_hit_04
    .db :trump_hit_05
    .db :trump_hit_06
    .db :trump_hit_07
    .db :trump_hit_08
    .db :trump_hit_09
    .db :trump_hit_10
    .db :trump_hit_11
    .db :trump_hit_12
    .db :trump_hit_13
    .db :trump_hit_14
    .db :trump_hit_15
    .db :trump_hit_16
    .db :trump_hit_17
    .db :trump_hit_18
    .db :trump_hit_19
    .db :trump_hit_20
trump_hit_addrs:
    .dw trump_hit_00
    .dw trump_hit_01
    .dw trump_hit_02
    .dw trump_hit_03
    .dw trump_hit_04
    .dw trump_hit_05
    .dw trump_hit_06
    .dw trump_hit_07
    .dw trump_hit_08
    .dw trump_hit_09
    .dw trump_hit_10
    .dw trump_hit_11
    .dw trump_hit_12
    .dw trump_hit_13
    .dw trump_hit_14
    .dw trump_hit_15
    .dw trump_hit_16
    .dw trump_hit_17
    .dw trump_hit_18
    .dw trump_hit_19
    .dw trump_hit_20

trump_fighter_pal:
.incbin "res/frames/trump_idle_00.pal"
trump_fighter_pal_end:

carney_idle_banks:
    .db :carney_idle_00
    .db :carney_idle_01
    .db :carney_idle_02
    .db :carney_idle_03
    .db :carney_idle_04
    .db :carney_idle_05
    .db :carney_idle_06
    .db :carney_idle_07
    .db :carney_idle_08
    .db :carney_idle_09
    .db :carney_idle_10
    .db :carney_idle_11
    .db :carney_idle_12
    .db :carney_idle_13
    .db :carney_idle_14
    .db :carney_idle_15
    .db :carney_idle_16
    .db :carney_idle_17
    .db :carney_idle_18
    .db :carney_idle_19
    .db :carney_idle_20
carney_idle_addrs:
    .dw carney_idle_00
    .dw carney_idle_01
    .dw carney_idle_02
    .dw carney_idle_03
    .dw carney_idle_04
    .dw carney_idle_05
    .dw carney_idle_06
    .dw carney_idle_07
    .dw carney_idle_08
    .dw carney_idle_09
    .dw carney_idle_10
    .dw carney_idle_11
    .dw carney_idle_12
    .dw carney_idle_13
    .dw carney_idle_14
    .dw carney_idle_15
    .dw carney_idle_16
    .dw carney_idle_17
    .dw carney_idle_18
    .dw carney_idle_19
    .dw carney_idle_20

carney_punch_banks:
    .db :carney_punch_00
    .db :carney_punch_01
    .db :carney_punch_02
    .db :carney_punch_03
    .db :carney_punch_04
    .db :carney_punch_05
    .db :carney_punch_06
    .db :carney_punch_07
    .db :carney_punch_08
    .db :carney_punch_09
    .db :carney_punch_10
    .db :carney_punch_11
    .db :carney_punch_12
    .db :carney_punch_13
    .db :carney_punch_14
    .db :carney_punch_15
    .db :carney_punch_16
    .db :carney_punch_17
    .db :carney_punch_18
    .db :carney_punch_19
    .db :carney_punch_20
carney_punch_addrs:
    .dw carney_punch_00
    .dw carney_punch_01
    .dw carney_punch_02
    .dw carney_punch_03
    .dw carney_punch_04
    .dw carney_punch_05
    .dw carney_punch_06
    .dw carney_punch_07
    .dw carney_punch_08
    .dw carney_punch_09
    .dw carney_punch_10
    .dw carney_punch_11
    .dw carney_punch_12
    .dw carney_punch_13
    .dw carney_punch_14
    .dw carney_punch_15
    .dw carney_punch_16
    .dw carney_punch_17
    .dw carney_punch_18
    .dw carney_punch_19
    .dw carney_punch_20

carney_kick_banks:
    .db :carney_kick_00
    .db :carney_kick_01
    .db :carney_kick_02
    .db :carney_kick_03
    .db :carney_kick_04
    .db :carney_kick_05
    .db :carney_kick_06
    .db :carney_kick_07
    .db :carney_kick_08
    .db :carney_kick_09
    .db :carney_kick_10
    .db :carney_kick_11
    .db :carney_kick_12
    .db :carney_kick_13
    .db :carney_kick_14
    .db :carney_kick_15
    .db :carney_kick_16
    .db :carney_kick_17
    .db :carney_kick_18
    .db :carney_kick_19
    .db :carney_kick_20
carney_kick_addrs:
    .dw carney_kick_00
    .dw carney_kick_01
    .dw carney_kick_02
    .dw carney_kick_03
    .dw carney_kick_04
    .dw carney_kick_05
    .dw carney_kick_06
    .dw carney_kick_07
    .dw carney_kick_08
    .dw carney_kick_09
    .dw carney_kick_10
    .dw carney_kick_11
    .dw carney_kick_12
    .dw carney_kick_13
    .dw carney_kick_14
    .dw carney_kick_15
    .dw carney_kick_16
    .dw carney_kick_17
    .dw carney_kick_18
    .dw carney_kick_19
    .dw carney_kick_20

carney_hit_banks:
    .db :carney_hit_00
    .db :carney_hit_01
    .db :carney_hit_02
    .db :carney_hit_03
    .db :carney_hit_04
    .db :carney_hit_05
    .db :carney_hit_06
    .db :carney_hit_07
    .db :carney_hit_08
    .db :carney_hit_09
    .db :carney_hit_10
    .db :carney_hit_11
    .db :carney_hit_12
    .db :carney_hit_13
    .db :carney_hit_14
    .db :carney_hit_15
    .db :carney_hit_16
    .db :carney_hit_17
    .db :carney_hit_18
    .db :carney_hit_19
    .db :carney_hit_20
carney_hit_addrs:
    .dw carney_hit_00
    .dw carney_hit_01
    .dw carney_hit_02
    .dw carney_hit_03
    .dw carney_hit_04
    .dw carney_hit_05
    .dw carney_hit_06
    .dw carney_hit_07
    .dw carney_hit_08
    .dw carney_hit_09
    .dw carney_hit_10
    .dw carney_hit_11
    .dw carney_hit_12
    .dw carney_hit_13
    .dw carney_hit_14
    .dw carney_hit_15
    .dw carney_hit_16
    .dw carney_hit_17
    .dw carney_hit_18
    .dw carney_hit_19
    .dw carney_hit_20

carney_fighter_pal:
.incbin "res/frames/carney_idle_00.pal"
carney_fighter_pal_end:

.ends
